### PR TITLE
Updated scan table for Croatia after DVB-T to DVB-T2 migration

### PR DESCRIPTION
**Pull request by ferencek**
The title says it all.

### CODE REVIEW

**Comment by muzena** [comment]
@Flole998  
I think you should rebase and sync dtv-scan-tables with upstream repo and commit changes from this fork to upstream, and add some note to users to commit their dtv-scan-tables changes to upstream dtv-scan-tables repo instead this fork then you can easily sync this fork as needed.

@ferencek 
I see you live in Zagreb.
I add this [scan tables to upstream repo DVB-T2/C](https://github.com/crazycat69/dtv-scan-tables/pull/19/files)
I can't receive and scan data for [L-ZA MUXL1]
Can you scan it if you receive this mux using [w_scan2](https://github.com/stefantalpalaru/w_scan2) and command
`w_scan2 -ft2 -5 -c HR > dvb_t2.conf` and update data for [[L-ZA MUXL1]](https://github.com/crazycat69/dtv-scan-tables/blob/master/dvb-t/hr-All)
and 
`w_scan2 -ft2 -X -c HR > hr-Zagreb.conf` and add more/missing channels/frequencies if you receive them to [hr-Zagreb.conf file](https://github.com/crazycat69/dtv-scan-tables/blob/master/channels-conf/dvb-t/hr-Zagreb.conf)

**Comment by ferencek** [comment]
@muzena, I had difficulty running `w_scan2` on my RPi4 to which the TV tuner is hooked up
```
$ ./w_scan2 -ft2 -5 -c HR > dvb_t2.conf

w_scan2-1.0.13 (compiled for DVB API 5.11)
https://github.com/stefantalpalaru/w_scan2

using settings for CROATIA
DVB aerial
DVB-T Europe
scan type TERRESTRIAL, delivery system SYS_DVBT2, channellist 4
output format initial tuning data (dvbv5scan)
WARNING: could not guess your codepage. Falling back to 'UTF-8'
output charset 'UTF-8', use -C <charset> to override
Info: using DVB adapter auto detection.
        /dev/dvb/adapter0/frontend0 -> TERRESTRIAL "Silicon Labs Si2168": very good :-))

Using TERRESTRIAL frontend (adapter /dev/dvb/adapter0/frontend0)
-_-_-_-_ Getting frontend capabilities-_-_-_-_ 
Using DVB API 5.11
frontend 'Silicon Labs Si2168' supports
DVB-T2
INVERSION_AUTO
QAM_AUTO
TRANSMISSION_MODE_AUTO
GUARD_INTERVAL_AUTO
HIERARCHY_AUTO
FEC_AUTO
BANDWIDTH_AUTO not supported, trying 6/7/8 MHz.
FREQ (48.00MHz ... 870.00MHz)
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_ 
Scanning DVB-T2...
Scanning 7MHz frequencies...
177500: plp0 (time: 00:01.289) 
184500: plp0 (time: 00:03.329) 
191500: plp0 (time: 00:05.379) 
198500: plp0 (time: 00:07.419) 
205500: plp0 (time: 00:09.459) 
212500: plp0 (time: 00:11.499) 
219500: plp0 (time: 00:13.539) 
226500: plp0 (time: 00:15.579) 
Scanning 8MHz frequencies...
474000: plp0 (time: 00:17.619) 
482000: plp0 (time: 00:19.659) 
490000: plp0 (time: 00:21.699) 
498000: plp0 (time: 00:23.739) 
506000: plp0 (time: 00:25.789)         signal ok:       QAM_AUTO f = 506000 kHz I999B8C999D999T999G999Y999P0 (0:0:0)
        QAM_AUTO f = 506000 kHz I999B8C999D999T999G999Y999P0 (0:0:0) : updating transport_stream_id: -> (0:0:10)
        QAM_AUTO f = 506000 kHz I999B8C999D999T999G999Y999P0 (0:0:10) : updating network_id -> (0:12545:10)
514000: plp0 (time: 00:32.439) 
522000: plp0 (time: 00:34.479) 
530000: plp0 (time: 00:36.509) 
538000: plp0 (time: 00:36.819) 
546000: plp0 (time: 00:38.859) 
554000: plp0 (time: 00:40.899) 
562000: plp0 (time: 00:42.939) 
570000: plp0 (time: 00:44.979) 
578000: plp0 (time: 00:47.019) 
586000: plp0 (time: 00:49.059) 
594000: plp0 (time: 00:51.099) 
602000: plp0 (time: 00:53.129) 
610000: plp0 (time: 00:55.179) 
618000: plp0 (time: 00:57.219) 
626000: plp0 (time: 00:59.259) 
634000: plp0 (time: 00:59.619) 
642000: plp0 (time: 01:01.659) 
650000: plp0 (time: 01:03.699) 
658000: plp0 (time: 01:08.128) 
666000: plp0 (time: 01:10.178) 
674000: plp0 (time: 01:12.218) 
682000: plp0 (time: 01:14.258) 
690000: plp0 (time: 01:16.298) 
698000: plp0 (time: 01:16.758) 
706000: plp0 (time: 01:18.788) 
714000: plp0 (time: 01:20.828) 
722000: plp0 (time: 01:22.858) 
730000: plp0 (time: 01:24.898) 
738000: plp0 (time: 01:26.938) 
746000: plp0 (time: 01:28.978) 
754000: plp0 (time: 01:31.018) 
762000: plp0 (time: 01:33.058) 
770000: plp0 (time: 01:35.098) 
778000: plp0 (time: 01:37.138) 
786000: plp0 (time: 01:39.178) 
794000: plp0 (time: 01:41.218) 
802000: plp0 (time: 01:43.258) 
810000: plp0 (time: 01:45.298) 
818000: plp0 (time: 01:47.338) 
826000: plp0 (time: 01:49.378) 
834000: plp0 (time: 01:51.418) 
842000: plp0 (time: 01:53.468) 
850000: plp0 (time: 01:55.508) 
858000: plp0 (time: 01:57.538) 
tune to: QAM_AUTO f = 506000 kHz I999B8C999D999T999G999Y999P0 (0:12545:10) (time: 01:59.578) 
----------no signal----------
tune to: QAM_AUTO f = 506000 kHz I999B8C999D999T999G999Y999P0 (0:12545:10) (time: 01:59.888)  (no signal)
----------no signal----------

ERROR: Sorry - i couldn't get any working frequency/transponder
 Nothing to scan!!
 ```
 I'm not an expert and I'm not sure I fully understand the error.
 
On the other hand, it is quite likely I would not be able to scan it as it is a local multiplex targeting small area outside Zagreb on its West side. Similarly, I am also not receiving [d044-d045-d046 MUXL1] which is another local multiplex which is supposed to cover at least some parts of Zagreb. After googling around a bit, I came across https://5.196.93.23/dtv.php?mux=MUX-L-ZA&liste=1&live=502&lang=en from which I managed to collect the necessary info and I created a follow-up PR https://github.com/tvheadend/dtv-scan-tables/pull/99
 
The reason I was originally missing [L-ZA MUXL1] was because it was not listed in https://support.oiv.hr/reception/temp/DTV_channel_hr_tableOnly.aspx but I do see it listed in https://hr.wikipedia.org/wiki/Dodatak:Popis_oda%C5%A1ilja%C4%8Dkih_objekata_OiV-a

**Comment by muzena** [comment]
@ferencek 
Ok, w_scan2 radi dobro, `Silicon Labs Si2168` takav i ja imam adapter, w_scan2 rezultat znači da nije našao ni jedan program, nešto je našao na 506000 kHz al je preslab signal, prije pretraživanja programa treba ugasiti Tvheadend, takav rezultat obično dobim kad w_scan2 pretraživa programe bez ukopčane antene

**Comment by ferencek** [comment]
@muzena, da, nisam siguran zašto sken nije uspio. Prije skeniranja s `w_scan2` sam napravio `sudo systemctl stop tvheadend`, ali moguće da to nije bilo dovoljno.

**Pull request merged**
