### PR TITLE
Update ATSC mux list for new network names and remove deprecated muxes

### PR DESCRIPTION
**Pull request by edit4ever**
Updated ATSC folders and files to match new tvheadend network names -- resolves missing muxes

USA (and north america) no longer use channels above 51 (mux 695028615)  -- These frequencies have been reallocated to other uses.
Removed deprecated frequencies to speed up user scans.

### CODE REVIEW

**Comment by perexg** [comment]
What missing muxes this resolves? The renaming 'ATSC' -> 'ATSC-T' and 'DVBC/ANNEX_B' -> 'ATSC-C' does not follow the Linux dtv tables conventions...

I'm not against the fixes / additions of new muxes, but it should follow the dtv-tables... https://github.com/oliv3r/dtv-scan-tables.git

**Comment by edit4ever** [comment]
The issue appears on LibreELEC/OpenELEC systems when setting up an ATSC-T or ATSC-C network - not pre-defined muxes are found.  We have investigated the build and can see that the ATSC folder is being present in dvb-scan when the build compiles - but the tvheadend webui can not see any pre-defined muxes.  Once we changes the folders and delivery systems to match the new tvheadend network names, the predefined muxes appeared.  This is on new installs - if upgrading from older systems that had ATSC muxes present...those remained intact.  That may explain why you still see the predefines muxes in your tests.

[https://github.com/oliv3r/dtv-scan-tables.git](url) has not been updated to match the new network names that tvheadend swicthed to when break ATSC into ATSC-T and ATSC-C in December 2015.  Also, in the US, Mexico and Canada - channels 52 and higher (701Khz) have been deprecated as they are used for cellular wireless now.  Leaving them in the predefined muxes causes unneccessary scans and slows down the tvheadend setup.

As a final note - for older tvheadend setups (people who have not upgraded to 4.0+) you can leave the ATSC folder intact in dvb-scan and just add the new folders and files for ATSC-T and ATSC-C.  It will not cause any issues.

**Comment by perexg** [comment]
> The issue appears on LibreELEC/OpenELEC systems when setting up an ATSC-T or ATSC-C network - not pre-defined muxes are found. We have investigated the build and can see that the ATSC folder is being present in dvb-scan when the build compiles - but the tvheadend webui can not see any pre-defined muxes. Once we changes the folders and delivery systems to match the new tvheadend network names, the predefined muxes appeared. This is on new installs - if upgrading from older systems that had ATSC muxes present...those remained intact. That may explain why you still see the predefines muxes in your tests.

Could you show the file structure which cannot be loaded by tvh? It appears like a bug, but I don't see it when I run tvh from the developent tree on x86_64 (new install).

**Comment by edit4ever** [comment]
The LibreELEC builds have --bundle enabled...so I can't see the final folder structure.  However, in looking at the build folders, the dvb-scan folders are there.  The tests are being conducted on RPi builds.

Do you see the ATSC muxes when you build with bundle?

**Comment by perexg** [comment]
Yes, I tried --enable-bundle too and renamed 'data/dvb-scan' tree. All ATSC muxes are present.

Could you provide '--trace scanfile' for tvh binary when ATSC muxes are not visible? https://tvheadend.org/projects/tvheadend/wiki/Traces

**Comment by edit4ever** [comment]
> Could you provide '--trace scanfile' for tvh binary when ATSC muxes are not visible?

If you mean to grab that during the RPi build...I will do that later.
BTW - are you seeing the predefined muxes when you have an ATSC-T network or do you still only see ATSC as your network choice?

Also - please take a look at the builds at [http://build.mycvh.de/](url) and see if you see the issue.  These are for the LibreELEC OS.

**Comment by perexg** [comment]
> If you mean to grab that during the RPi build.

No, it's runtime option for the tvh binary.

> are you seeing the predefined muxes when you have an ATSC-T network

I'm talking about latest tvh (ATSC-T network), but the import from the scan files support both ATSC/ATSC-T strings...

**Comment by edit4ever** [comment]
We only see the predefined muxes if we pull the dvb-scan list from my repo that contains the new atsc-t/atsc-c folder structure.  No predefined muxes show for atsc-t/atsc-c networks if only the atsc folder is present in dvb-scan.  

Here is kodi log from a system with my repo:
`... output of cat /storage/.kodi/userdata/addon_data/service.tvheadend42/service.log
 LibreELEC release: S802.M8.arm-devel-20160720230230-r23239-g5a1c208
 LibreELEC git: 5a1c2081828386e2da674c909e3b3e862a34248f
2016-08-28 12:18:29.574 [   INFO] main: Log started
2016-08-28 12:18:29.587 [   INFO] http: Starting HTTP server 0.0.0.0:9981
2016-08-28 12:18:29.590 [   INFO] htsp: Starting HTSP server 0.0.0.0:9982
2016-08-28 12:18:29.593 [  ERROR] satips: use --satip_bindaddr parameter to select the local IP for SAT>IP
2016-08-28 12:18:29.593 [  ERROR] satips: using Google lookup (might block the task until timeout)
2016-08-28 12:18:29.623 [   INFO] config: loaded
2016-08-28 12:18:29.623 [   INFO] config: scanfile (re)initialization with path <none>
2016-08-28 12:18:30.204 [   INFO] scanfile: DVB-S - loaded 1 regions with 113 networks
2016-08-28 12:18:30.204 [   INFO] scanfile: DVB-T - loaded 41 regions with 1056 networks
2016-08-28 12:18:30.205 [   INFO] scanfile: DVB-C - loaded 17 regions with 55 networks
2016-08-28 12:18:30.205 [   INFO] scanfile: ATSC-T - loaded 1 regions with 1 networks
2016-08-28 12:18:30.205 [   INFO] scanfile: ATSC-C - loaded 1 regions with 3 networks
2016-08-28 12:18:30.205 [   INFO] scanfile: ISDB-T - loaded 2 regions with 1000 networks
`

Here is one from a system using standard build:

`[ NOTICE] START: HTS Tvheadend version 4.1.2195 ~ LibreELEC Tvh-addon v8.0.104 started, running as PID:1119 UID:0 GID:39, CWD:/ CNF:/storage/.kodi/userdata/addon_data/service.tvheadend42
2016-08-28 10:22:52.214 [   INFO] scanfile: DVB-S - loaded 1 regions with 113 networks
2016-08-28 10:22:52.215 [   INFO] scanfile: DVB-T - loaded 44 regions with 1106 networks
2016-08-28 10:22:52.215 [   INFO] scanfile: DVB-C - loaded 17 regions with 55 networks
2016-08-28 10:22:52.215 [   INFO] scanfile: ISDB-T - loaded 2 regions with 1000 networks
`

**Comment by perexg** [comment]
Provide the trace as requested to see why your binary reject the imported data.

**Comment by CvH** [comment]
http://cvh.libreelec.tv/Tvheadend/debug.log (could crash the browser if opened instead of saved!)

**Comment by perexg** [comment]
Please, retry with tvh master... There was 4MB limit total for all files, but it's not enough for latest dvbv5 format....

**Comment by CvH** [comment]
@perexg with this pr or just clean master ?

**Comment by perexg** [comment]
Clean master.. I've not accepted these changes. The bug was in tvh.

**Comment by CvH** [comment]
http://cvh.libreelec.tv/Tvheadend/debug_4.1.2208.log
looks better now (no idea if this works)

**Comment by perexg** [comment]
It looks that everything is fine:

<pre>
12:42:34.431 [  TRACE]:scanfile: load file us-ATSC-center-frequencies-8VSB (processed bytes 5174407)
12:42:34.431 [  TRACE]:scanfile: mux ATSC-T freq 57028615 mod VSB/8
12:42:34.431 [  TRACE]:scanfile: mux ATSC-T freq 63028615 mod VSB/8
12:42:34.431 [  TRACE]:scanfile: mux ATSC-T freq 69028615 mod VSB/8
</pre>

**Comment by perexg** [comment]
@edit4ever  : Please, don't create new directories, do all changes in atsc/ tree... Also, please, rebase to the master of tvheadend dtv tables..

**Comment by edit4ever** [comment]
Thanks - fix is working.  I will rebase and just submit the removal of deprecated ATSC frequencies.

**Pull request closed without merging**
